/* Generated by Cython 0.29.6 */

#ifndef __PYX_HAVE__pywt___extensions___pywt
#define __PYX_HAVE__pywt___extensions___pywt

struct WaveletObject;
struct ContinuousWaveletObject;

/* "pywt/_extensions/_pywt.pxd":26
 *     have_c99_complex = 0
 * 
 * cdef public class Wavelet [type WaveletType, object WaveletObject]:             # <<<<<<<<<<<<<<
 *     cdef wavelet.DiscreteWavelet* w
 * 
 */
struct WaveletObject {
  PyObject_HEAD
  DiscreteWavelet *w;
  PyObject *name;
  PyObject *number;
};

/* "pywt/_extensions/_pywt.pxd":32
 *     cdef readonly number
 * 
 * cdef public class ContinuousWavelet [type ContinuousWaveletType, object ContinuousWaveletObject]:             # <<<<<<<<<<<<<<
 *     cdef wavelet.ContinuousWavelet* w
 * 
 */
struct ContinuousWaveletObject {
  PyObject_HEAD
  ContinuousWavelet *w;
  PyObject *name;
  PyObject *number;
  PyObject *dt;
};

#ifndef __PYX_HAVE_API__pywt___extensions___pywt

#ifndef __PYX_EXTERN_C
  #ifdef __cplusplus
    #define __PYX_EXTERN_C extern "C"
  #else
    #define __PYX_EXTERN_C extern
  #endif
#endif

#ifndef DL_IMPORT
  #define DL_IMPORT(_T) _T
#endif

__PYX_EXTERN_C DL_IMPORT(PyTypeObject) WaveletType;
__PYX_EXTERN_C DL_IMPORT(PyTypeObject) ContinuousWaveletType;

#endif /* !__PYX_HAVE_API__pywt___extensions___pywt */

/* WARNING: the interface of the module init function changed in CPython 3.5. */
/* It now returns a PyModuleDef instance instead of a PyModule instance. */

#if PY_MAJOR_VERSION < 3
PyMODINIT_FUNC init_pywt(void);
#else
PyMODINIT_FUNC PyInit__pywt(void);
#endif

#endif /* !__PYX_HAVE__pywt___extensions___pywt */
